---
- hosts: rabbitmq
  remote_user: root
  tasks:   
      - name: copy html
        template: src=templates/hosts.j2 dest=/etc/hosts
#      - name: test
#        shell: echo {{id}} >> /root/test1.txt
